import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Config } from "./types.ts";
import { PLAYWRIGHT_VERSION, STATE_DIR } from "./types.ts";

export const DEFAULTS: Omit<Config, "start"> = {
  readyPath: "/",
  readyTimeoutMs: 60_000,
  checkTimeoutMs: 30_000,
  copy: [".env", ".env.local", ".env.development", ".env.development.local"]
};

export function configPath(root: string): string {
  return join(root, STATE_DIR, "config.json");
}

interface PackageJson {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  scripts?: Record<string, string>;
}

/**
 * A best guess at how to start the app on a port of our choosing. Framework
 * CLIs are called directly when we can, because `npm run dev` often pins a
 * port in the script itself, and two apps on one port is the one thing a
 * proof can't survive. `detected` is printed by `init` so the guess is never
 * silent.
 */
export function detectConfig(root: string): { config: Config; detected: string; known: boolean } {
  let pkg: PackageJson = {};
  try {
    pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as PackageJson;
  } catch {
    // no package.json: fall through to the generic default
  }
  const deps = { ...pkg.dependencies, ...pkg.devDependencies };
  const scripts = pkg.scripts ?? {};
  const pick = (start: string, detected: string, known = true) => ({ config: { start, ...DEFAULTS }, detected, known });
  if (deps.next) return pick("npx next dev -p {port}", "Next.js");
  if (deps.vite) return pick("npx vite --port {port} --strictPort", "Vite");
  if (scripts.dev) return pick("npm run dev", 'the "dev" script (PORT is set; make sure the app reads it)');
  if (scripts.start) return pick("npm start", 'the "start" script (PORT is set; make sure the app reads it)');
  return pick("npm start", `nothing recognisable: edit "start" in ${STATE_DIR}/config.json`, false);
}

export function loadConfig(root: string): Config {
  const path = configPath(root);
  if (!existsSync(path)) throw new Error(`No ${STATE_DIR}/config.json here. Run "thisisfine init" in the project root first.`);
  const raw = JSON.parse(readFileSync(path, "utf8")) as Partial<Config>;
  const config = { ...DEFAULTS, ...raw } as Config;
  if (typeof config.start !== "string" || config.start.trim() === "") throw new Error(`${path}: "start" must be a command string`);
  if (typeof config.readyPath !== "string" || !config.readyPath.startsWith("/")) throw new Error(`${path}: "readyPath" must start with /`);
  for (const k of ["readyTimeoutMs", "checkTimeoutMs"] as const) {
    if (!Number.isFinite(config[k]) || config[k] <= 0) throw new Error(`${path}: "${k}" must be a positive number`);
  }
  if (!Array.isArray(config.copy) || !config.copy.every((c) => typeof c === "string")) throw new Error(`${path}: "copy" must be a list of paths`);
  return config;
}

const PLAYWRIGHT_CONFIG = `// Generated by thisisfine. Every run-specific value arrives through the
// environment, so this one file serves proofs and gates alike.
import { defineConfig } from "@playwright/test";

const env = process.env;
export default defineConfig({
  testDir: "./checks",
  testMatch: "**/*.spec.ts",
  timeout: Number(env.THISISFINE_TIMEOUT || 30000),
  retries: Number(env.THISISFINE_RETRIES || 0),
  workers: 2,
  outputDir: env.THISISFINE_OUTPUT_DIR || "./runs/last/artifacts",
  reporter: [["json", { outputFile: env.THISISFINE_REPORT || "./runs/last/report.json" }]],
  use: {
    baseURL: env.THISISFINE_BASE_URL,
    browserName: "chromium",
    screenshot: env.THISISFINE_SCREENSHOT === "on" ? "on" : "only-on-failure",
    trace: "off"
  }
});
`;

const GITIGNORE = `runs/
node_modules/
`;

/**
 * Lays out `.thisisfine/`. Playwright gets its own package.json in there so
 * the user's dependency tree is never touched; the version is pinned so a
 * check that passed yesterday runs in the same browser today.
 */
export function writeScaffold(root: string, config: Config): string[] {
  const dir = join(root, STATE_DIR);
  mkdirSync(join(dir, "checks"), { recursive: true });
  const written: string[] = [];
  const write = (name: string, content: string, overwrite: boolean) => {
    const path = join(dir, name);
    if (!overwrite && existsSync(path)) return;
    writeFileSync(path, content);
    written.push(`${STATE_DIR}/${name}`);
  };
  write("config.json", JSON.stringify(config, null, 2) + "\n", false);
  write("playwright.config.mjs", PLAYWRIGHT_CONFIG, true);
  write("package.json", JSON.stringify({
    name: "thisisfine-checks", private: true, type: "module",
    devDependencies: { "@playwright/test": PLAYWRIGHT_VERSION }
  }, null, 2) + "\n", true);
  write(".gitignore", GITIGNORE, true);
  write("checks/.gitkeep", "", false);
  return written;
}
