/**
 * The small libraries a check imports to reach the app from outside: the
 * HTTP API through `THISISFINE_BASE_URL`, the cli through `THISISFINE_CLI`,
 * and files through a scratch directory. One per runner, same three verbs,
 * so a promise reads the same whatever language checks it. Generated into
 * `.thisisfine/` (and regenerated by every `init`), never into the app.
 */

export const PYTEST_VERSION = "8.3.3";
export const REQUESTS_VERSION = "2.32.3";

/** Playwright fixtures. A check does `import { test, expect } from "../tif";`. */
export const TIF_TS = String.raw`// Generated by thisisfine; "thisisfine init" rewrites it.
// Checks import from here to reach the app from outside:
//   test("...", async ({ page, request, run, write, read }) => { ... })
import { test as base, expect } from "@playwright/test";
import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

export interface Result { code: number; out: string; err: string }

interface Fixtures {
  /** The cli's working directory for this test (fresh each time). */
  work: string;
  /** Runs the configured cli with these args; never throws on a non-zero exit. */
  run: (args: string[], opts?: { input?: string }) => Promise<Result>;
  /** Writes a file inside the scratch directory, for the cli to read. */
  write: (path: string, text: string) => string;
  /** Reads a file the cli wrote in the scratch directory (null when it isn't there). */
  read: (path: string) => string | null;
}

function inside(work: string, path: string): string {
  const full = resolve(work, path);
  if (relative(work, full).startsWith("..")) throw new Error("thisisfine: " + path + " is outside the scratch directory");
  return full;
}

export const test = base.extend<Fixtures>({
  work: async ({}, use, info) => {
    const dir = join(info.outputDir, "work");
    mkdirSync(dir, { recursive: true });
    await use(dir);
  },
  run: async ({ work }, use) => {
    await use((args, opts = {}) => new Promise<Result>((done, fail) => {
      const cli = JSON.parse(process.env.THISISFINE_CLI || "null") as string[] | null;
      if (!cli) return fail(new Error('thisisfine: no cli to run. Set "cli" in .thisisfine/config.json.'));
      const child = spawn(cli[0]!, [...cli.slice(1), ...args], { env: { ...process.env, THISISFINE_WORK: work }, windowsHide: true });
      let out = "";
      let err = "";
      child.stdout.on("data", (c) => (out += c));
      child.stderr.on("data", (c) => (err += c));
      child.on("error", fail);
      child.on("close", (code) => done({ code: code ?? 1, out, err }));
      child.stdin.end(opts.input ?? "");
    }));
  },
  write: async ({ work }, use) => {
    await use((path, text) => {
      const full = inside(work, path);
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, text);
      return full;
    });
  },
  read: async ({ work }, use) => {
    await use((path) => {
      const full = inside(work, path);
      return existsSync(full) ? readFileSync(full, "utf8") : null;
    });
  }
});

export { expect };
`;

/** pytest helper. A check does `from thisisfine_check import api, run, write, read`. */
export const PY_HELPER = String.raw`"""Generated by thisisfine; "thisisfine init" rewrites it.

Checks reach the app from outside, never by importing it:

    from thisisfine_check import api, run, write, read

    def test_rejects_an_expired_token():
        r = api.get("/me", headers={"Authorization": "Bearer expired"})
        assert r.status_code == 401
"""
import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

import requests

BASE_URL = os.environ.get("THISISFINE_BASE_URL", "").rstrip("/")
_ROOT = Path(os.environ.get("THISISFINE_WORK") or tempfile.mkdtemp(prefix="thisisfine-"))


def work():
    """This test's scratch directory, where the cli runs (fresh for every test)."""
    test = os.environ.get("PYTEST_CURRENT_TEST", "outside-a-test").split(" ")[0].split("::")[-1]
    full = _ROOT / re.sub(r"[^\w.-]+", "_", test) / "work"
    full.mkdir(parents=True, exist_ok=True)
    return full


class _Api(requests.Session):
    """A requests.Session whose relative URLs go to the app."""

    def __init__(self):
        super().__init__()
        self.trust_env = False  # a system proxy must not sit between a check and localhost

    def request(self, method, url, *args, **kwargs):
        if url.startswith("/"):
            if not BASE_URL:
                raise RuntimeError('thisisfine: no app to call. Set "start" in .thisisfine/config.json.')
            url = BASE_URL + url
        kwargs.setdefault("timeout", 30)
        return super().request(method, url, *args, **kwargs)


api = _Api()


@dataclass
class Result:
    code: int
    out: str
    err: str


def run(*args, input=None, timeout=60):
    """Runs the configured cli with these args. Never raises on a non-zero exit."""
    cli = json.loads(os.environ.get("THISISFINE_CLI") or "null")
    if not cli:
        raise RuntimeError('thisisfine: no cli to run. Set "cli" in .thisisfine/config.json.')
    p = subprocess.run(
        [*cli, *(str(a) for a in args)],
        input=input, capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=timeout, env={**os.environ, "THISISFINE_WORK": str(work())},
    )
    return Result(p.returncode, p.stdout, p.stderr)


def _inside(path):
    base = work().resolve()
    full = (base / path).resolve()
    if base not in (full, *full.parents):
        raise ValueError(f"thisisfine: {path} is outside the scratch directory")
    return full


def write(path, text):
    """Writes a file inside the scratch directory, for the cli to read."""
    full = _inside(path)
    full.parent.mkdir(parents=True, exist_ok=True)
    full.write_text(text, encoding="utf-8")
    return full


def read(path):
    """Reads a file the cli wrote in the scratch directory, or None."""
    full = _inside(path)
    return full.read_text(encoding="utf-8") if full.exists() else None
`;

export const PYTEST_INI = `# Generated by thisisfine. Every check file is its own test module.
[pytest]
addopts = --import-mode=importlib -p no:cacheprovider
pythonpath = .
python_files = *.py
python_functions = test_*
`;

export const PY_REQUIREMENTS = `# Generated by thisisfine: what checks run on, pinned so a check that
# passed yesterday runs on the same libraries today.
pytest==${PYTEST_VERSION}
requests==${REQUESTS_VERSION}
`;

export const GO_MODULE = "thisisfine.local/checks";

export const GO_MOD = `// Generated by thisisfine. The checks' own module: it never requires or
// replaces the app's, so a check can only reach the app from outside.
module ${GO_MODULE}

go 1.21
`;

/** Go helper. A check does `import "thisisfine.local/checks/tif"`. */
export const GO_TIF = String.raw`// Generated by thisisfine; "thisisfine init" rewrites it.
//
// Package tif lets a check reach the app from outside, never by importing it:
//
//	func TestDryRunWritesNothing(t *testing.T) {
//		tif.Write(t, "in.txt", "hello")
//		r := tif.Run(t, "--dry-run", "in.txt")
//		if r.Code != 0 || tif.Exists(t, "out.txt") { t.Fatalf("...") }
//	}
package tif

import (
	"encoding/json"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

// Result is what the cli did.
type Result struct {
	Code int
	Out  string
	Err  string
}

var unsafe = regexp.MustCompile("[^A-Za-z0-9_.-]+")

// Work is this test's scratch directory, where the cli runs (fresh for every test).
func Work(t testing.TB) string {
	t.Helper()
	root := os.Getenv("THISISFINE_WORK")
	if root == "" {
		root = os.TempDir()
	}
	dir := filepath.Join(root, unsafe.ReplaceAllString(t.Name(), "_"), "work")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	return dir
}

// Run runs the configured cli with these args. A non-zero exit is a Result, not a failure.
func Run(t testing.TB, args ...string) Result {
	t.Helper()
	return RunInput(t, "", args...)
}

// RunInput is Run with stdin.
func RunInput(t testing.TB, input string, args ...string) Result {
	t.Helper()
	var cli []string
	if err := json.Unmarshal([]byte(os.Getenv("THISISFINE_CLI")), &cli); err != nil || len(cli) == 0 {
		t.Fatal("thisisfine: no cli to run. Set \"cli\" in .thisisfine/config.json.")
	}
	cmd := exec.Command(cli[0], append(cli[1:], args...)...)
	cmd.Env = append(os.Environ(), "THISISFINE_WORK="+Work(t))
	cmd.Stdin = strings.NewReader(input)
	var out, errb strings.Builder
	cmd.Stdout, cmd.Stderr = &out, &errb
	err := cmd.Run()
	code := 0
	if err != nil {
		ee, ok := err.(*exec.ExitError)
		if !ok {
			t.Fatalf("thisisfine: couldn't run the cli: %v", err)
		}
		code = ee.ExitCode()
	}
	return Result{Code: code, Out: out.String(), Err: errb.String()}
}

func inside(t testing.TB, path string) string {
	t.Helper()
	work := Work(t)
	full := filepath.Join(work, path)
	if rel, err := filepath.Rel(work, full); err != nil || strings.HasPrefix(rel, "..") {
		t.Fatalf("thisisfine: %s is outside the scratch directory", path)
	}
	return full
}

// Write writes a file inside the scratch directory, for the cli to read.
func Write(t testing.TB, path, text string) string {
	t.Helper()
	full := inside(t, path)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(text), 0o644); err != nil {
		t.Fatal(err)
	}
	return full
}

// Read reads a file the cli wrote in the scratch directory; "" when it isn't there.
func Read(t testing.TB, path string) string {
	t.Helper()
	b, err := os.ReadFile(inside(t, path))
	if err != nil {
		return ""
	}
	return string(b)
}

// Exists says whether the cli left a file in the scratch directory.
func Exists(t testing.TB, path string) bool {
	t.Helper()
	_, err := os.Stat(inside(t, path))
	return err == nil
}

// Response is what the app answered, body read in full.
type Response struct {
	Status int
	Header http.Header
	Body   string
}

// JSON decodes the body into v, failing the check if it isn't JSON.
func (r Response) JSON(t testing.TB, v any) {
	t.Helper()
	if err := json.Unmarshal([]byte(r.Body), v); err != nil {
		t.Fatalf("not JSON (%v): %s", err, r.Body)
	}
}

// Client calls the app through THISISFINE_BASE_URL.
type Client struct {
	t    testing.TB
	base string
	http *http.Client
}

// API returns a client for the app under test.
func API(t testing.TB) *Client {
	t.Helper()
	base := strings.TrimRight(os.Getenv("THISISFINE_BASE_URL"), "/")
	if base == "" {
		t.Fatal("thisisfine: no app to call. Set \"start\" in .thisisfine/config.json.")
	}
	// Proxy: nil, so a system proxy never sits between a check and localhost.
	return &Client{t: t, base: base, http: &http.Client{Timeout: 30 * time.Second, Transport: &http.Transport{Proxy: nil}}}
}

// Do sends a request. header is name, value pairs. A body that starts with { or [ is sent as JSON.
func (c *Client) Do(method, path, body string, header ...string) Response {
	c.t.Helper()
	var rd io.Reader
	if body != "" {
		rd = strings.NewReader(body)
	}
	req, err := http.NewRequest(method, c.base+path, rd)
	if err != nil {
		c.t.Fatal(err)
	}
	if b := strings.TrimSpace(body); strings.HasPrefix(b, "{") || strings.HasPrefix(b, "[") {
		req.Header.Set("Content-Type", "application/json")
	}
	for i := 0; i+1 < len(header); i += 2 {
		req.Header.Set(header[i], header[i+1])
	}
	res, err := c.http.Do(req)
	if err != nil {
		c.t.Fatalf("%s %s: %v", method, path, err)
	}
	defer res.Body.Close()
	b, _ := io.ReadAll(res.Body)
	return Response{Status: res.StatusCode, Header: res.Header, Body: string(b)}
}

// Get is Do("GET", ...).
func (c *Client) Get(path string, header ...string) Response {
	c.t.Helper()
	return c.Do("GET", path, "", header...)
}

// Post is Do("POST", ...).
func (c *Client) Post(path, body string, header ...string) Response {
	c.t.Helper()
	return c.Do("POST", path, body, header...)
}
`;
